spring:
    application:
      name: nyist-aduit
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
      url: jdbc:mysql://192.168.110.240/aduit?characterEncoding=utf-8&useSSL=false
      #type: com.alibaba.druid.pool.DruidDataSource

    jpa:
      show-sql: true
    mvc:
      view:
        prefix: /WEB-INF/jsp/
        suffix: .jsp
